package edu.psu.plantvilagedemo;

public class DefaultPlants {
    public static final String[] PLANT_NAMES = {
            "Healthy",
            "Early blight",
            "Late blight",
            "Leaf mold",
            "Septoria leaf spot",
            "Tetranychus urticae",
            "Bacterial spot",
            "Mosaic virus",
            "Target spot",
            "YellowLeaf curl virus"
    };

    public static final String[] PLANT_DESCRIPTIONS = {
            "A healthy tomato plant exhibits strong growth, vibrant green leaves, and produces an abundance of fruit. It is free from diseases and pests, which allows it to thrive and reach its full potential. Proper care, including adequate watering, well-draining soil, and sufficient nutrients, helps to maintain the plant's health. Regular monitoring and implementing preventive measures can also minimize the risk of diseases, ensuring a bountiful harvest.",
            "Early blight, caused by the fungus Alternaria solani, is a common disease affecting tomato plants. It typically presents as dark, concentric rings on the lower leaves, eventually leading to yellowing and dropping off. If left untreated, the disease can spread upwards and affect the fruit, causing sunken, dark spots. Management includes crop rotation, removing infected plant debris, adequate plant spacing for air circulation, and application of appropriate fungicides.",
            "Late blight is a destructive tomato disease caused by the water mold Phytophthora infestans. It manifests as water-soaked, irregularly shaped lesions on leaves that rapidly turn brown and necrotic. Under moist conditions, white, mold-like growth may be visible on the lower leaf surface. The disease can progress quickly, affecting stems and fruits, causing them to rot. Preventive measures include selecting resistant varieties, proper plant spacing, and applying fungicides.",
            "Leaf mold is a fungal disease caused by Fulvia fulva (previously known as Cladosporium fulvum) that primarily affects greenhouse-grown tomatoes. The fungus thrives in high humidity and low light conditions. Symptoms include pale green or yellow spots on the upper leaf surface, which later turn brown and necrotic, and olive-green velvety growth on the lower leaf surface. To control leaf mold, improve air circulation, reduce humidity, and use resistant cultivars or fungicides when necessary.",
            "Septoria leaf spot, caused by the fungus Septoria lycopersici, is a common disease in tomato plants. It begins as small, water-soaked spots on the lower leaves, which later develop into circular lesions with gray centers and dark margins. Infected leaves may yellow and drop off, reducing fruit production. Control methods include crop rotation, removing infected debris, adequate plant spacing for air circulation, and applying fungicides when needed.",
            "Tetranychus urticae, commonly known as the two-spotted spider mite, is a tiny arachnid that feeds on tomato plants, among other crops. These mites pierce plant cells and suck out the contents, causing stippling, yellowing, and browning of the leaves. Severe infestations can lead to leaf drop, reduced fruit production, and poor plant vigor. Fine webbing may also be visible on the leaves and stems, as the mites use it for protection and to move between plant parts.",
            "Bacterial spot, caused by several species of Xanthomonas, is a common disease affecting tomato plants. It manifests as small, water-soaked lesions on leaves, stems, and fruits that can later become necrotic and surrounded by a yellow halo. The disease can lead to defoliation and reduced fruit yield, especially under warm and humid conditions. Bacterial spot is often spread through contaminated seed, irrigation water, or infected plant debris.",
            "Mosaic viruses, such as the Tobacco mosaic virus (TMV) and Tomato mosaic virus (ToMV), are viral diseases that infect tomato plants. Symptoms include mottled, yellow-green leaves with a mosaic-like pattern, stunted growth, and reduced fruit production. The virus can be mechanically transmitted through contaminated tools, hands, or infected plant material. Once a plant is infected, there is no cure, and the best course of action is to remove and destroy the infected plant to prevent further spread.",
            "Target spot, caused by the fungus Corynespora cassiicola, is a fungal disease affecting tomato plants. It presents as small, water-soaked spots on the leaves that can enlarge and develop into target-like concentric rings with a dark brown center and lighter brown margins. Severe infections can lead to leaf drop, fruit rot, and reduced yield. The fungus thrives in warm, humid conditions and can be spread through rain splashes, contaminated tools, or infected plant debris.",
            "Yellow Leaf Curl Virus (TYLCV) is a viral disease transmitted by the whitefly Bemisia tabaci. It causes tomato plants to exhibit symptoms such as upward curling, yellowing, and thickening of the leaves, along with stunted growth and reduced fruit production. Infected plants may also develop small, deformed fruits. Since there is no cure for this viral disease, prevention and management strategies focus on controlling the whitefly population and using virus-resistant tomato cultivars."
    };

    public static final String[] PLANT_PRESCRIPTIONS = {
            "It is healthy as it should be!",
            "To treat early blight, remove the affected leaves and plant debris to prevent further spread of the disease. Apply a copper-based fungicide or biofungicides containing Bacillus subtilis or Trichoderma strains, following the label instructions for application rates and frequencies. Ensure proper plant spacing for air circulation, and practice crop rotation with non-solanaceous crops to break the disease cycle. Keeping the plant healthy with adequate nutrients will also help it better resist infection.",
            "For late blight, act quickly to prevent the rapid spread of the disease. Remove and destroy infected plants or plant parts. Apply fungicides containing copper, chlorothalonil, or other active ingredients labeled for late blight control, following the manufacturer's recommendations. Timely application of these products is crucial to protect healthy plants. Implementing preventive measures, such as proper plant spacing, reducing leaf wetness, and selecting resistant cultivars, can help avoid future outbreaks.",
            "When treating leaf mold, start by removing and discarding affected leaves and plant debris. Apply an appropriate fungicide, such as those containing copper or sulfur, following the label directions for proper application rates and intervals. To help prevent future infections, improve air circulation by pruning and maintaining proper plant spacing, and reduce humidity levels within the greenhouse. Additionally, selecting resistant tomato cultivars can help in managing the disease.",
            "To treat Septoria leaf spot, begin by removing infected leaves and plant debris to reduce the fungal inoculum. Apply a fungicide with an active ingredient effective against Septoria lycopersici, such as chlorothalonil, copper, or mancozeb, adhering to the label instructions for proper usage. Enhance air circulation and reduce leaf wetness through proper plant spacing and watering practices. Implementing crop rotation with non-host plants can also help break the disease cycle and prevent future infections.",
            "To control two-spotted spider mites, start by regularly monitoring plants for signs of infestation. Remove and discard heavily infested leaves or plants. Introduce predatory mites, such as Phytoseiulus persimilis or Neoseiulus californicus, as a biological control measure. Insecticidal soaps, horticultural oils, or miticides can also be used to manage mite populations, but always follow the label instructions for proper application. Maintaining proper humidity and avoiding excessive nitrogen fertilization can help reduce the risk of spider mite infestations.",
            "To treat bacterial spot, begin by removing infected leaves and plant debris. Apply a copper-based bactericide, such as copper hydroxide or copper sulfate, following label recommendations for application rates and frequencies. Ensure proper plant spacing for air circulation and avoid overhead watering to reduce leaf wetness. Practice crop rotation and use pathogen-free seeds or transplants to help prevent future infections.",
            "There is no cure for mosaic virus infections in tomato plants. Upon detection, promptly remove and destroy infected plants to prevent the spread of the virus. Sanitize tools, hands, and equipment regularly to avoid mechanical transmission. Implement a rigorous weed control program, as some weeds can harbor the virus. Using virus-resistant cultivars and practicing crop rotation can also help minimize the risk of infection.",
            "For target spot, remove and discard infected leaves and plant debris to reduce fungal inoculum. Apply appropriate fungicides, such as those containing chlorothalonil or copper, following label instructions for proper application rates and intervals. Enhance air circulation and reduce leaf wetness by providing proper plant spacing and avoiding overhead watering. Implementing crop rotation with non-host plants can help break the disease cycle and prevent future infections.",
            "To manage Yellow Leaf Curl Virus, focus on prevention and controlling its whitefly vector. Regularly inspect plants for whiteflies and virus symptoms, and promptly remove any infected plants to prevent further spread. Employ sticky traps or insecticides, such as neonicotinoids or pyrethroids, in accordance with label instructions to manage whitefly populations. Alternatively, introduce biological control agents like lacewings or lady beetles. Use reflective mulches to repel whiteflies and reduce their populations. Choose virus-resistant tomato cultivars and practice proper crop rotation to minimize the risk of infection. Ensure good plant health through proper nutrition and watering, as healthier plants are more resilient to pests and diseases."
    };
}
